import './styles.css';
import { supabase, ensureAnonymousSession } from './supabase';
import { importInventoryCsv } from './importCsv';
import { importManageBookingsCsv } from './importBookings';
import { recogniseFiles } from './ocr';
import { normalizeSerial, serialVariants } from './serial';
import { augmentedRows, bulkBarcodeRows, downloadCsv } from './exportCsv';
import type { AuditResult, AuditSession, BulkCount, InventoryAsset, KitCheck, ManageBookingRow, OcrCandidate, QueueStatus, ReconcileOutcome } from './types';

const app = document.querySelector<HTMLDivElement>('#app')!;
let sessions: AuditSession[] = [], currentSession: AuditSession | null = null;
let assets: InventoryAsset[] = [], results: AuditResult[] = [], bulkCounts: BulkCount[] = [];
let bookingRows: ManageBookingRow[] = [], kitChecks: KitCheck[] = [], candidates: OcrCandidate[] = [];
let technician = localStorage.getItem('siso-technician') ?? '';
let activeView: 'dashboard'|'kits'|'reconcile'|'bulk'|'export'|'queue'|'debug' = location.hash === '#debug' ? 'debug' : 'dashboard';
let queueFilter: QueueStatus = 'second_pass';
let pendingCandidate: OcrCandidate | null = null;
let realtimeChannel: ReturnType<typeof supabase.channel> | null = null;
let selectedKitGroup = '';
let selectedPresentKits = new Set<string>();
let realtimeStatus: 'disconnected'|'connecting'|'subscribed'|'error' = 'disconnected';
let realtimeDetail = '';
let lastDebugError = '';
let authUserId = '';
let debugPressTimer: number | null = null;

const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const resultFor=(id:string)=>results.find(r=>r.inventory_asset_id===id);
const cleanBarcode=(v:string|null|undefined)=>String(v??'').replace(/\s+/g,'').toUpperCase();
function kitParts(barcode:string|null|undefined){const b=cleanBarcode(barcode);const m=b.match(/^BMS([A-Z]+?)(\d+)$/);return m?{barcode:b,group:m[1]!,number:m[2]!,code:`${m[1]} ${Number(m[2])}`} : null;}
function counts(){const c:Record<QueueStatus,number>={not_checked:assets.length,reconciled:0,second_pass:0,further_action:0};for(const r of results){c[r.queue_status]++;c.not_checked--;}return c;}
function uniqueKits(){const map=new Map<string,{barcode:string;group:string;number:string;code:string;asset:InventoryAsset}>();for(const a of assets){const p=kitParts(a.barcode);if(p&&!map.has(p.barcode))map.set(p.barcode,{...p,asset:a});}return [...map.values()].sort((a,b)=>a.group.localeCompare(b.group)||Number(a.number)-Number(b.number));}
function bookingFor(barcode:string){return bookingRows.filter(r=>cleanBarcode(r.asset_barcode)===barcode);}
function isOutState(state:string){return !/^(available|returned|complete|completed|cancelled|canceled|in store)$/i.test(state.trim());}

async function loadSessions(){const {data,error}=await supabase.from('audit_sessions').select('*').order('created_at',{ascending:false});if(error)throw error;sessions=data??[];const stored=localStorage.getItem('siso-session');currentSession=sessions.find(s=>s.id===stored)??sessions.find(s=>s.status==='open')??sessions[0]??null;}
async function loadSessionData(){if(!currentSession){assets=[];results=[];bulkCounts=[];bookingRows=[];kitChecks=[];return;}const [a,r,b,m,k]=await Promise.all([
  supabase.from('inventory_assets').select('*').eq('audit_session_id',currentSession.id).order('source_row'),
  supabase.from('audit_results').select('*').eq('audit_session_id',currentSession.id),
  supabase.from('bulk_counts').select('*').eq('audit_session_id',currentSession.id).order('created_at',{ascending:false}),
  supabase.from('manage_booking_rows').select('*').eq('audit_session_id',currentSession.id),
  supabase.from('kit_checks').select('*').eq('audit_session_id',currentSession.id)
]);
 for(const x of [a,r,b,m,k])if(x.error)throw x.error;
 assets=a.data??[];results=r.data??[];bulkCounts=b.data??[];bookingRows=m.data??[];kitChecks=k.data??[];
 const groups=[...new Set(uniqueKits().map(k=>k.group))];if(!selectedKitGroup&&groups.length)selectedKitGroup=groups[0]!;
}

function render(){const c=counts();app.innerHTML=`<div class="shell"><header><div><h1 id="debug-trigger">SiSo Companion</h1><p>${esc(currentSession?.name??'No reconciliation selected')}</p></div>${currentSession?`<button id="change-session" class="header-button">Change</button>`:''}</header><main>${!technician?techSetup():viewHtml(c)}</main>${technician?navHtml():''}${pendingCandidate?reasonModal():''}</div>`;bindEvents();}
const techSetup=()=>`<section class="card"><h2>Who is using this phone?</h2><label for="tech">Initials or short name</label><input id="tech" maxlength="20" autocomplete="name"><button id="save-tech" class="full">Continue</button></section>`;
function viewHtml(c:Record<QueueStatus,number>){if(activeView==='debug')return debugHtml(c);if(activeView==='kits')return kitsHtml();if(activeView==='reconcile')return reconcileHtml();if(activeView==='bulk')return bulkHtml();if(activeView==='export')return exportHtml(c);if(activeView==='queue')return queueHtml();return dashboardHtml(c);}

function scientificSerials(){return assets.filter(a=>/^\s*[+-]?(?:\d+(?:\.\d+)?|\.\d+)[eE][+-]?\d+\s*$/.test(a.serial));}
function duplicateSerialGroups(){const by=new Map<string,InventoryAsset[]>();for(const a of assets){if(!a.serial_normalized)continue;by.set(a.serial_normalized,[...(by.get(a.serial_normalized)??[]),a]);}return [...by.entries()].filter(([,rows])=>rows.length>1).sort((a,b)=>b[1].length-a[1].length);}
function debugHtml(c:Record<QueueStatus,number>){
 const scientific=scientificSerials(),duplicates=duplicateSerialGroups();
 const ocrExact=candidates.filter(x=>x.matchType==='exact').length,ocrSub=candidates.filter(x=>x.matchType==='substitution').length,ocrNone=candidates.filter(x=>x.matchType==='none').length;
 const kitSummary={reconciled:0,siso_update:0,missing:0,second_pass:0};for(const k of kitChecks)kitSummary[k.comparison_status]++;
 return `<section class="card debug-card"><div class="row"><div><h2>Developer diagnostics</h2><p class="muted">Hidden pilot support panel</p></div><button id="close-debug" class="secondary">Close</button></div>
 <div class="grid metrics debug-metrics">${metric('Stock rows',assets.length,'not_checked')}${metric('Bookings',bookingRows.length,'not_checked')}${metric('Results',results.length,'not_checked')}${metric('Bulk counts',bulkCounts.length,'not_checked')}</div>
 <h3>Connection</h3><dl class="debug-list"><div><dt>Supabase authentication</dt><dd>${authUserId?`Connected · ${esc(authUserId.slice(0,8))}…`:'No active user'}</dd></div><div><dt>Realtime</dt><dd><span class="badge ${realtimeStatus==='subscribed'?'ok':realtimeStatus==='error'?'bad':'warn'}">${esc(realtimeStatus)}</span> ${esc(realtimeDetail)}</dd></div><div><dt>Current reconciliation</dt><dd>${esc(currentSession?.name??'None')} ${currentSession?`· ${esc(currentSession.id.slice(0,8))}…`:''}</dd></div><div><dt>Network</dt><dd>${navigator.onLine?'Online':'Offline'}</dd></div></dl>
 <h3>Import health</h3><div class="mini-metrics"><span><strong>${assets.length}</strong> serialised rows</span><span><strong>${scientific.length}</strong> scientific notation</span><span><strong>${duplicates.length}</strong> duplicate serial groups</span><span><strong>${uniqueKits().length}</strong> derived kits</span></div>
 ${scientific.length?`<details><summary>Scientific-notation serials (${scientific.length})</summary>${scientific.slice(0,50).map(a=>`<div class="debug-row"><strong>${esc(a.serial)}</strong><span>${esc(a.asset_name)} · ${esc(a.bag_label??a.barcode??'No kit')}</span></div>`).join('')}${scientific.length>50?`<p class="muted">Showing first 50.</p>`:''}</details>`:''}
 ${duplicates.length?`<details><summary>Duplicate serial groups (${duplicates.length})</summary>${duplicates.slice(0,30).map(([serial,rows])=>`<div class="debug-row"><strong>${esc(serial)} × ${rows.length}</strong><span>${rows.map(a=>esc(a.bag_label??a.barcode??a.asset_name)).join(' · ')}</span></div>`).join('')}${duplicates.length>30?`<p class="muted">Showing first 30.</p>`:''}</details>`:''}
 <h3>OCR</h3><div class="mini-metrics"><span><strong>${candidates.length}</strong> candidates</span><span><strong>${ocrExact}</strong> exact</span><span><strong>${ocrSub}</strong> substitutions</span><span><strong>${ocrNone}</strong> unmatched</span></div>
 ${candidates.length?`<details><summary>Latest OCR candidates</summary>${candidates.slice(0,40).map(x=>`<div class="debug-row"><strong>${esc(x.raw)}</strong><span>${esc(x.matchType)} · confidence ${Math.round(x.confidence)}${x.sourceFile?` · ${esc(x.sourceFile)}`:''}</span></div>`).join('')}</details>`:''}
 <h3>Queues</h3><div class="mini-metrics"><span><strong>${c.reconciled}</strong> reconciled</span><span><strong>${c.second_pass}</strong> second pass</span><span><strong>${c.further_action}</strong> further action</span><span><strong>${c.not_checked}</strong> not checked</span></div>
 <h3>Kit checks</h3><div class="mini-metrics"><span><strong>${kitSummary.reconciled}</strong> reconciled</span><span><strong>${kitSummary.siso_update}</strong> SiSo updates</span><span><strong>${kitSummary.missing}</strong> missing</span><span><strong>${kitSummary.second_pass}</strong> second pass</span></div>
 ${lastDebugError?`<div class="status debug-error"><strong>Last error</strong><pre>${esc(lastDebugError)}</pre></div>`:''}
 <button id="refresh-debug" class="full">Refresh diagnostics</button></section>`;
}

function dashboardHtml(c:Record<QueueStatus,number>){const kc={reconciled:0,siso_update:0,missing:0,second_pass:0};for(const k of kitChecks)kc[k.comparison_status]++;return `<div class="grid metrics">${metric('Reconciled',c.reconciled,'reconciled')}${metric('Second pass',c.second_pass,'second_pass')}${metric('Further action',c.further_action,'further_action')}${metric('Not checked',c.not_checked,'not_checked')}</div>
<section class="card"><h2>Kit presence</h2><div class="mini-metrics"><span><strong>${kitChecks.length}</strong> checked</span><span><strong>${kc.siso_update}</strong> SiSo updates</span><span><strong>${kc.missing}</strong> missing</span></div><button class="full" data-view="kits">Open kit board</button></section>
<section class="card"><h2>Shared reconciliation</h2>${currentSession?`<p><strong>${esc(currentSession.name)}</strong></p><p class="muted">${assets.length} serialised stock records · ${bookingRows.length} Manage Bookings rows.</p>`:`<label>Reconciliation name</label><input id="new-session-name" value="2026 Stock Reconciliation"><button id="create-session" class="full">Create shared reconciliation</button>`}</section>
${currentSession?`<section class="card"><h2>Import SiSo files</h2><label>Stock CSV</label><input id="csv-file" type="file" accept=".csv,text/csv"><button id="import-csv" class="full">Import serialised assets</button><div id="import-status" class="status hidden" aria-live="polite"></div><hr><label>Manage Bookings CSV</label><input id="bookings-file" type="file" accept=".csv,text/csv"><button id="import-bookings" class="full secondary">Import current bookings</button><div id="bookings-status" class="status hidden" aria-live="polite"></div></section>`:''}
<section class="card"><div class="row"><div><strong>Technician</strong><div class="muted">${esc(technician)}</div></div><button id="change-tech" class="secondary">Change</button></div></section>`;}
const metric=(label:string,n:number,q:QueueStatus)=>`<button class="metric metric-button" data-queue="${q}"><span>${label}</span><strong>${n}</strong></button>`;

function kitsHtml(){const kits=uniqueKits(),groups=[...new Set(kits.map(k=>k.group))];const groupKits=kits.filter(k=>k.group===selectedKitGroup);const checked=new Map(kitChecks.map(k=>[k.kit_barcode,k]));return `<section class="card"><h2>Kit presence check</h2><p class="muted">Choose the kit family, tap every kit physically present, then reconcile the family against the uploaded Manage Bookings list. Untapped kits are treated as absent.</p><div class="group-tabs">${groups.map(g=>`<button data-kit-group="${esc(g)}" class="${g===selectedKitGroup?'active':''}">${esc(g)}</button>`).join('')}</div><div class="kit-wall">${groupKits.map(k=>{const prior=checked.get(k.barcode);const selected=selectedPresentKits.has(k.barcode);const cls=selected?'selected':prior?`status-${prior.comparison_status}`:'';return `<button class="kit-tile ${cls}" data-kit="${k.barcode}"><strong>${esc(k.number)}</strong><span>${prior?esc(prior.comparison_status.replaceAll('_',' ')):'Not checked'}</span></button>`}).join('')}</div><p class="muted">${selectedPresentKits.size} kit${selectedPresentKits.size===1?'':'s'} selected as physically present.</p><button id="reconcile-kit-group" class="full" ${!groupKits.length||!bookingRows.length?'disabled':''}>Reconcile ${esc(selectedKitGroup)} against SiSo</button>${!bookingRows.length?'<div class="status">Import Manage Bookings before running the comparison.</div>':''}</section>${kitResultsHtml()}`;}
function kitResultsHtml(){const rows=kitChecks.filter(k=>!selectedKitGroup||k.kit_group===selectedKitGroup).sort((a,b)=>a.kit_code.localeCompare(b.kit_code,undefined,{numeric:true}));if(!rows.length)return '';return `<section class="card"><h2>${esc(selectedKitGroup)} results</h2>${rows.map(k=>`<div class="asset"><div class="row"><strong>${esc(k.kit_code)}</strong><span class="badge ${k.comparison_status==='reconciled'?'ok':k.comparison_status==='missing'?'bad':'warn'}">${esc(k.comparison_status.replaceAll('_',' '))}</span></div><div>${k.physical_state==='present'?'Physically present':'Physically absent'} · SiSo: ${esc(k.booking_state??'not shown as out')}</div>${k.detail?`<div class="muted">${esc(k.detail)}</div>`:''}</div>`).join('')}</section>`;}

function reconcileHtml(){return `<section class="card"><h2>Photograph serial labels</h2><p class="muted">Choose one or several photos. OCR runs on this phone and images are not uploaded.</p><input id="ocr-files" type="file" accept="image/*" capture="environment" multiple><button id="run-ocr" class="full" ${!assets.length?'disabled':''}>Read photos</button><div id="ocr-status" class="status hidden" aria-live="polite"></div></section><section class="card"><h2>Manual serial fallback</h2><div class="row"><input id="manual-serial" autocomplete="off" autocapitalize="characters" placeholder="Enter serial"><button id="manual-search">Find</button></div></section>${candidateHtml()}`;}
function candidateHtml(){if(!candidates.length)return `<section class="card"><h2>Results</h2><p class="muted">OCR and manual matches appear here.</p></section>`;return `<section class="card"><h2>Batch results</h2>${candidates.map((c,i)=>candidateCard(c,i)).join('')}</section>`;}
function candidateCard(c:OcrCandidate,i:number){
 if(c.matches&&c.matches.length>1)return `<div class="asset"><span class="badge warn">${c.matches.length} SiSo matches</span><div class="asset-title">Serial ${esc(c.raw)}</div><p class="muted">Select the item by its kit.</p>${c.matches.map((a,j)=>assetActions(a,c,i,j)).join('')}</div>`;
 if(!c.asset)return `<div class="asset"><span class="badge bad">Not found</span><label>OCR text</label><div class="row"><input data-correct-index="${i}" value="${esc(c.raw)}"><button data-relookup="${i}" class="secondary">Try again</button></div><div class="actions"><button data-unknown="${i}" class="danger">Log for further action</button></div></div>`;
 const existing=resultFor(c.asset.id);return `<div class="asset"><span class="badge ${c.matchType==='exact'?'ok':'warn'}">${c.matchType==='exact'?'Matched':'Check OCR reading'}</span><div class="asset-title">${esc(c.asset.asset_name)}</div><div class="muted">${esc([c.asset.make,c.asset.model].filter(Boolean).join(' '))} · Serial ${esc(c.asset.serial)}</div><div class="kit-label">Correct kit: ${esc(c.asset.bag_label??c.asset.barcode??'No SiSo barcode')}</div>${existing?`<div class="status">Already recorded by ${esc(existing.verified_by)}</div>`:`<div class="actions"><button data-outcome="already_correct" data-index="${i}">Already in correct kit</button><button data-outcome="returned" data-index="${i}">Returned to correct kit</button><button data-outcome="could_not_return" data-index="${i}" class="warn">Needs further action</button></div>`}</div>`;}
function assetActions(a:InventoryAsset,c:OcrCandidate,i:number,j:number){const existing=resultFor(a.id);return `<div class="match-choice"><strong>${esc(a.asset_name)}</strong><div class="muted">${esc(a.make)} ${esc(a.model)}</div><div class="kit-label">Correct kit: ${esc(a.bag_label??a.barcode??'No SiSo barcode')}</div>${existing?`<div class="status">Already recorded by ${esc(existing.verified_by)}</div>`:`<div class="actions"><button data-match-outcome="already_correct" data-index="${i}" data-match="${j}">Already in correct kit</button><button data-match-outcome="returned" data-index="${i}" data-match="${j}">Returned</button><button data-match-outcome="could_not_return" data-index="${i}" data-match="${j}" class="warn">Further action</button></div>`}</div>`;}
function bulkHtml(){const total=bulkCounts.reduce((s,c)=>s+(c.barcode_required?c.quantity:0),0);return `<section class="card"><h2>Bulk count</h2><label>Item type</label><input id="bulk-name" placeholder="Headphones"><label>Quantity found</label><input id="bulk-qty" type="number" min="1" inputmode="numeric"><label>Proposed QR prefix (optional)</label><input id="bulk-prefix" autocapitalize="characters" placeholder="HPS"><label>Label method</label><select id="bulk-method"><option value="small_adhesive">Small adhesive</option><option value="key_fob">Key fob</option><option value="standard_adhesive">Standard adhesive</option><option value="flag_label">Flag label</option><option value="pending">Decide later</option></select><label class="check"><input id="bulk-barcode" type="checkbox" checked> Needs an individual QR label per item</label><label>Notes</label><textarea id="bulk-notes" rows="2"></textarea><button id="save-bulk" class="full">Add to QR queue</button></section><section class="card"><h2>QR label queue</h2><p><strong>${total}</strong> labels required from bulk counts.</p>${bulkCounts.map(c=>`<div class="asset"><strong>${esc(c.item_name)}</strong> — ${c.quantity}<div class="muted">${esc(c.proposed_prefix??'No prefix yet')} · ${esc(c.label_method.replaceAll('_',' '))} · ${esc(c.counted_by)}</div></div>`).join('')||'<p class="muted">No bulk counts yet.</p>'}</section>`;}
function queueHtml(){const rows=queueFilter==='not_checked'?assets.filter(a=>!resultFor(a.id)).map(a=>({asset:a,result:null})):results.filter(r=>r.queue_status===queueFilter).map(r=>({asset:assets.find(a=>a.id===r.inventory_asset_id),result:r})).filter(x=>x.asset);return `<section class="card"><div class="row"><h2>${esc(queueFilter.replaceAll('_',' '))}</h2><button id="back-dashboard" class="secondary">Back</button></div>${rows.length?rows.map(({asset:a,result:r})=>`<div class="asset"><div class="asset-title">${esc(a!.asset_name)}</div><div class="muted">${esc(a!.serial)} · ${esc(a!.bag_label??a!.barcode??'No kit')}</div>${r?`<div>${esc(r.exception_reason??r.outcome??'')}</div>${r.queue_status!=='reconciled'?`<button data-resolve="${r.id}" class="full">Mark resolved</button>`:''}`:''}</div>`).join(''):'<p class="muted">Nothing in this queue.</p>'}</section>`;}
function exportHtml(c:Record<QueueStatus,number>){return `<section class="card"><h2>Export</h2><p class="muted">Original SiSo columns plus reconciliation fields.</p><button id="export-full" class="full">Full audit CSV</button><button id="export-leftovers" class="full secondary">Outstanding items CSV</button><button id="export-bulk" class="full secondary">Bulk QR queue CSV</button></section><section class="card"><h2>Current totals</h2><p>${c.reconciled} reconciled · ${c.second_pass} second pass · ${c.further_action} further action · ${c.not_checked} not checked.</p></section>`;}
function navHtml(){return `<nav><button data-view="dashboard" class="${activeView==='dashboard'?'active':''}">Home</button><button data-view="kits" class="${activeView==='kits'?'active':''}">Kits</button><button data-view="reconcile" class="${activeView==='reconcile'?'active':''}">OCR</button><button data-view="bulk" class="${activeView==='bulk'?'active':''}">Bulk</button><button data-view="export" class="${activeView==='export'?'active':''}">Export</button></nav>`;}
function reasonModal(){return `<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><h2>Why can’t it be returned?</h2><div class="reason-grid"><button data-reason="Correct kit currently on loan" data-stage="second_pass">Correct kit currently on loan</button><button data-reason="Current kit currently on loan" data-stage="second_pass">Current kit currently on loan</button><button data-reason="Correct kit not found" data-stage="second_pass">Correct kit not found</button><button data-reason="Requires investigation" data-stage="further_action" class="warn">Requires investigation</button><button data-reason="Other" data-stage="further_action" class="secondary">Other</button><button id="cancel-reason" class="secondary">Cancel</button></div></section></div>`;}

function lookup(raw:string):OcrCandidate{const n=normalizeSerial(raw),by=new Map<string,InventoryAsset[]>();for(const a of assets)by.set(a.serial_normalized,[...(by.get(a.serial_normalized)??[]),a]);const exact=by.get(n),variant=exact?undefined:serialVariants(n).find(v=>by.has(v)),matches=exact??(variant?by.get(variant):undefined);return{raw,normalized:variant??n,confidence:100,asset:matches?.length===1?matches[0]:undefined,matches,matchType:exact?'exact':variant?'substitution':'none'};}
async function saveOutcome(c:OcrCandidate,outcome:ReconcileOutcome,reason:string|null=null,stage:'second_pass'|'further_action'='second_pass'){if(!c.asset||!currentSession)return;const queue:QueueStatus=outcome==='could_not_return'?stage:'reconciled';const record={inventory_asset_id:c.asset.id,audit_session_id:currentSession.id,queue_status:queue,audit_stage:queue==='reconciled'?'complete':stage,outcome,exception_reason:reason,next_action:queue==='second_pass'?'Recheck kit availability':queue==='further_action'?'Investigate or update SiSo':null,label_required:c.asset.label_required,label_method:c.asset.label_method,verified_by:technician,verified_at:new Date().toISOString()};const {error}=await supabase.from('audit_results').upsert(record,{onConflict:'inventory_asset_id'});if(error)alert(error.message);pendingCandidate=null;await loadSessionData();render();}
async function reconcileKitGroup(){if(!currentSession)return;const groupKits=uniqueKits().filter(k=>k.group===selectedKitGroup);const now=new Date().toISOString();const records=groupKits.map(k=>{const present=selectedPresentKits.has(k.barcode),bookings=bookingFor(k.barcode),active=bookings.find(b=>isOutState(b.state));let comparison_status:'reconciled'|'siso_update'|'missing'|'second_pass'='reconciled',detail:string|null=null;if(present&&active){comparison_status='siso_update';detail=`Physically present but SiSo shows ${active.state}${active.booked_by?` to ${active.booked_by}`:''}.`;}else if(!present&&!active){comparison_status='missing';detail='Not physically present and not shown as out in Manage Bookings.';}else if(!present&&active){detail=`Physically absent and correctly shown as ${active.state}${active.booked_by?` to ${active.booked_by}`:''}.`;}else{detail='Physically present and not shown as out.';}return{audit_session_id:currentSession!.id,kit_barcode:k.barcode,kit_code:k.code,kit_group:k.group,physical_state:present?'present':'absent',booking_state:active?.state??null,comparison_status,detail,checked_by:technician,checked_at:now,updated_at:now};});const {error}=await supabase.from('kit_checks').upsert(records,{onConflict:'audit_session_id,kit_barcode'});if(error)alert(error.message);else{selectedPresentKits.clear();await loadSessionData();render();}}

function bindEvents(){
 const debugTrigger=document.querySelector<HTMLElement>('#debug-trigger');
 const openDebug=()=>{activeView='debug';location.hash='debug';render();};
 debugTrigger?.addEventListener('pointerdown',()=>{debugPressTimer=window.setTimeout(openDebug,1200);});
 for(const eventName of ['pointerup','pointercancel','pointerleave'] as const)debugTrigger?.addEventListener(eventName,()=>{if(debugPressTimer!==null){clearTimeout(debugPressTimer);debugPressTimer=null;}});
 document.querySelector('#close-debug')?.addEventListener('click',()=>{activeView='dashboard';history.replaceState(null,'',location.pathname+location.search);render();});
 document.querySelector('#refresh-debug')?.addEventListener('click',async()=>{try{await loadSessionData();render();}catch(e){lastDebugError=e instanceof Error?e.message:String(e);render();}});
 document.querySelector('#save-tech')?.addEventListener('click',()=>{const v=(document.querySelector<HTMLInputElement>('#tech')?.value??'').trim();if(v){technician=v;localStorage.setItem('siso-technician',v);render();}});
 document.querySelector('#change-tech')?.addEventListener('click',()=>{technician='';localStorage.removeItem('siso-technician');render();});
 document.querySelector('#change-session')?.addEventListener('click',()=>{localStorage.removeItem('siso-session');currentSession=null;render();});
 document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.addEventListener('click',()=>{activeView=b.dataset.view as typeof activeView;render();}));
 document.querySelectorAll<HTMLButtonElement>('[data-queue]').forEach(b=>b.addEventListener('click',()=>{queueFilter=b.dataset.queue as QueueStatus;activeView='queue';render();}));
 document.querySelector('#back-dashboard')?.addEventListener('click',()=>{activeView='dashboard';render();});
 document.querySelector('#create-session')?.addEventListener('click',async()=>{const name=(document.querySelector<HTMLInputElement>('#new-session-name')?.value??'').trim();if(!name)return;const {data,error}=await supabase.from('audit_sessions').insert({name,created_by:technician}).select().single();if(error)alert(error.message);else{localStorage.setItem('siso-session',data.id);await refresh();}});
 document.querySelector('#import-csv')?.addEventListener('click',async()=>{const file=document.querySelector<HTMLInputElement>('#csv-file')?.files?.[0],status=document.querySelector<HTMLDivElement>('#import-status');if(!file||!currentSession||!status)return;status.classList.remove('hidden');status.textContent='Importing…';try{const r=await importInventoryCsv(file,currentSession.id);status.textContent=`Imported ${r.imported}; skipped ${r.skippedNoSerial} without serials; ${r.duplicateSerials} duplicate serial rows.`;await loadSessionData();render();}catch(e){lastDebugError=e instanceof Error?e.message:String(e);status.textContent=lastDebugError;}});
 document.querySelector('#import-bookings')?.addEventListener('click',async()=>{const file=document.querySelector<HTMLInputElement>('#bookings-file')?.files?.[0],status=document.querySelector<HTMLDivElement>('#bookings-status');if(!file||!currentSession||!status)return;status.classList.remove('hidden');status.textContent='Importing current bookings…';try{const r=await importManageBookingsCsv(file,currentSession.id);status.textContent=`Imported ${r.imported} booking rows covering ${r.uniqueBarcodes} assets.`;await loadSessionData();render();}catch(e){lastDebugError=e instanceof Error?e.message:String(e);status.textContent=lastDebugError;}});
 document.querySelectorAll<HTMLButtonElement>('[data-kit-group]').forEach(b=>b.addEventListener('click',()=>{selectedKitGroup=b.dataset.kitGroup??'';selectedPresentKits.clear();render();}));
 document.querySelectorAll<HTMLButtonElement>('[data-kit]').forEach(b=>b.addEventListener('click',()=>{const code=b.dataset.kit!;selectedPresentKits.has(code)?selectedPresentKits.delete(code):selectedPresentKits.add(code);render();}));
 document.querySelector('#reconcile-kit-group')?.addEventListener('click',reconcileKitGroup);
 document.querySelector('#run-ocr')?.addEventListener('click',async()=>{const files=[...(document.querySelector<HTMLInputElement>('#ocr-files')?.files??[])],status=document.querySelector<HTMLDivElement>('#ocr-status');if(!files.length||!status)return;status.classList.remove('hidden');try{candidates=await recogniseFiles(files,assets,m=>status.textContent=m);status.textContent=`Found ${candidates.length} candidate serials.`;render();}catch(e){lastDebugError=e instanceof Error?e.message:String(e);status.textContent=lastDebugError;}});
 document.querySelector('#manual-search')?.addEventListener('click',()=>{const raw=(document.querySelector<HTMLInputElement>('#manual-serial')?.value??'').trim();if(raw){candidates=[lookup(raw),...candidates];render();}});
 document.querySelectorAll<HTMLButtonElement>('[data-relookup]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.relookup),raw=document.querySelector<HTMLInputElement>(`[data-correct-index="${i}"]`)?.value??'';candidates[i]=lookup(raw);render();}));
 document.querySelectorAll<HTMLButtonElement>('[data-match-outcome]').forEach(b=>b.addEventListener('click',()=>{const base=candidates[Number(b.dataset.index)],asset=base?.matches?.[Number(b.dataset.match)];if(!base||!asset)return;const c={...base,asset,matches:[asset]};const o=b.dataset.matchOutcome as ReconcileOutcome;if(o==='could_not_return'){pendingCandidate=c;render();}else saveOutcome(c,o);}));
 document.querySelectorAll<HTMLButtonElement>('[data-outcome]').forEach(b=>b.addEventListener('click',()=>{const c=candidates[Number(b.dataset.index)];if(!c)return;const o=b.dataset.outcome as ReconcileOutcome;if(o==='could_not_return'){pendingCandidate=c;render();}else saveOutcome(c,o);}));
 document.querySelectorAll<HTMLButtonElement>('[data-reason]').forEach(b=>b.addEventListener('click',()=>{if(pendingCandidate)saveOutcome(pendingCandidate,'could_not_return',b.dataset.reason??'Other',b.dataset.stage as 'second_pass'|'further_action');}));
 document.querySelector('#cancel-reason')?.addEventListener('click',()=>{pendingCandidate=null;render();});
 document.querySelectorAll<HTMLButtonElement>('[data-unknown]').forEach(b=>b.addEventListener('click',async()=>{if(!currentSession)return;const c=candidates[Number(b.dataset.unknown)];if(!c)return;const {error}=await supabase.from('unknown_serials').insert({audit_session_id:currentSession.id,raw_serial:c.raw,normalized_serial:c.normalized,source:'ocr',queue_status:'further_action',reported_by:technician});if(error)alert(error.message);else alert('Logged for further action.');}));
 document.querySelectorAll<HTMLButtonElement>('[data-resolve]').forEach(b=>b.addEventListener('click',async()=>{const {error}=await supabase.from('audit_results').update({queue_status:'reconciled',audit_stage:'complete',next_action:null,updated_at:new Date().toISOString()}).eq('id',b.dataset.resolve);if(error)alert(error.message);await loadSessionData();render();}));
 document.querySelector('#save-bulk')?.addEventListener('click',async()=>{if(!currentSession)return;const name=(document.querySelector<HTMLInputElement>('#bulk-name')?.value??'').trim(),quantity=Number(document.querySelector<HTMLInputElement>('#bulk-qty')?.value??0);if(!name||quantity<1)return;const record={audit_session_id:currentSession.id,item_name:name,asset_type:name,quantity,barcode_required:document.querySelector<HTMLInputElement>('#bulk-barcode')?.checked??true,proposed_prefix:(document.querySelector<HTMLInputElement>('#bulk-prefix')?.value??'').trim().toUpperCase()||null,label_method:document.querySelector<HTMLSelectElement>('#bulk-method')?.value??'pending',queue_status:'barcode_queue',notes:(document.querySelector<HTMLTextAreaElement>('#bulk-notes')?.value??'').trim()||null,counted_by:technician};const {error}=await supabase.from('bulk_counts').insert(record);if(error)alert(error.message);await loadSessionData();render();});
 document.querySelector('#export-full')?.addEventListener('click',()=>downloadCsv('siso-companion-full-audit.csv',augmentedRows(assets,results)));
 document.querySelector('#export-leftovers')?.addEventListener('click',()=>downloadCsv('siso-companion-outstanding.csv',augmentedRows(assets,results).filter((_,i)=>{const r=resultFor(assets[i]!.id);return !r||r.queue_status==='second_pass'||r.queue_status==='further_action';})));
 document.querySelector('#export-bulk')?.addEventListener('click',()=>downloadCsv('siso-companion-bulk-qr-queue.csv',bulkBarcodeRows(bulkCounts)));
}
async function subscribe(){if(realtimeChannel)await supabase.removeChannel(realtimeChannel);realtimeStatus='disconnected';realtimeDetail='';if(!currentSession)return;realtimeStatus='connecting';realtimeChannel=supabase.channel(`audit:${currentSession.id}`).on('postgres_changes',{event:'*',schema:'public',table:'audit_results',filter:`audit_session_id=eq.${currentSession.id}`},async()=>{await loadSessionData();render();}).on('postgres_changes',{event:'*',schema:'public',table:'bulk_counts',filter:`audit_session_id=eq.${currentSession.id}`},async()=>{await loadSessionData();render();}).on('postgres_changes',{event:'*',schema:'public',table:'kit_checks',filter:`audit_session_id=eq.${currentSession.id}`},async()=>{await loadSessionData();render();}).subscribe((status:string)=>{realtimeDetail=status;if(status==='SUBSCRIBED')realtimeStatus='subscribed';else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'){realtimeStatus='error';lastDebugError=`Realtime: ${status}`;}else if(status==='CLOSED')realtimeStatus='disconnected';else realtimeStatus='connecting';if(activeView==='debug')render();});}
async function refresh(){await loadSessions();await loadSessionData();render();await subscribe();}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(e=>{lastDebugError=e instanceof Error?e.message:String(e);console.error(e);}));
window.addEventListener('hashchange',()=>{if(location.hash==='#debug'){activeView='debug';render();}});
(async()=>{try{await ensureAnonymousSession();const {data}=await supabase.auth.getSession();authUserId=data.session?.user.id??'';await refresh();}catch(e){lastDebugError=e instanceof Error?e.message:String(e);app.innerHTML=`<div class="shell"><main><section class="card"><h2>Setup error</h2><p>${esc(lastDebugError)}</p></section></main></div>`;}})();
