import './styles.css';
import { supabase, ensureAnonymousSession } from './supabase';
import { importInventoryCsv } from './importCsv';
import { recogniseFiles } from './ocr';
import { normalizeSerial, serialVariants } from './serial';
import { augmentedRows, bulkBarcodeRows, downloadCsv } from './exportCsv';
import type { AuditResult, AuditSession, BulkCount, InventoryAsset, OcrCandidate, QueueStatus, ReconcileOutcome } from './types';

const app = document.querySelector<HTMLDivElement>('#app')!;
let sessions: AuditSession[] = [], currentSession: AuditSession | null = null;
let assets: InventoryAsset[] = [], results: AuditResult[] = [], bulkCounts: BulkCount[] = [], candidates: OcrCandidate[] = [];
let technician = localStorage.getItem('siso-technician') ?? '';
let activeView: 'dashboard'|'reconcile'|'bulk'|'export'|'queue' = 'dashboard';
let queueFilter: QueueStatus = 'second_pass';
let pendingCandidate: OcrCandidate | null = null;
let realtimeChannel: ReturnType<typeof supabase.channel> | null = null;

const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const resultFor=(id:string)=>results.find(r=>r.inventory_asset_id===id);
function counts(){const c:Record<QueueStatus,number>={not_checked:assets.length,reconciled:0,second_pass:0,further_action:0};for(const r of results){c[r.queue_status]++;c.not_checked--;}return c;}

async function loadSessions(){const {data,error}=await supabase.from('audit_sessions').select('*').order('created_at',{ascending:false});if(error)throw error;sessions=data??[];const stored=localStorage.getItem('siso-session');currentSession=sessions.find(s=>s.id===stored)??sessions.find(s=>s.status==='open')??sessions[0]??null;}
async function loadSessionData(){if(!currentSession){assets=[];results=[];bulkCounts=[];return;}const [a,r,b]=await Promise.all([supabase.from('inventory_assets').select('*').eq('audit_session_id',currentSession.id).order('source_row'),supabase.from('audit_results').select('*').eq('audit_session_id',currentSession.id),supabase.from('bulk_counts').select('*').eq('audit_session_id',currentSession.id).order('created_at',{ascending:false})]);if(a.error)throw a.error;if(r.error)throw r.error;if(b.error)throw b.error;assets=a.data??[];results=r.data??[];bulkCounts=b.data??[];}

function render(){const c=counts();app.innerHTML=`<div class="shell"><header><div><h1>SiSo Companion</h1><p>${esc(currentSession?.name??'No reconciliation selected')}</p></div>${currentSession?`<button id="change-session" class="header-button">Change</button>`:''}</header><main>${!technician?techSetup():viewHtml(c)}</main>${technician?navHtml():''}${pendingCandidate?reasonModal():''}</div>`;bindEvents();}
const techSetup=()=>`<section class="card"><h2>Who is using this phone?</h2><label for="tech">Initials or short name</label><input id="tech" maxlength="20" autocomplete="name"><button id="save-tech" class="full">Continue</button></section>`;
function viewHtml(c:Record<QueueStatus,number>){if(activeView==='reconcile')return reconcileHtml();if(activeView==='bulk')return bulkHtml();if(activeView==='export')return exportHtml(c);if(activeView==='queue')return queueHtml();return dashboardHtml(c);}
function dashboardHtml(c:Record<QueueStatus,number>){return `<div class="grid metrics">${metric('Reconciled',c.reconciled,'reconciled')}${metric('Second pass',c.second_pass,'second_pass')}${metric('Further action',c.further_action,'further_action')}${metric('Not checked',c.not_checked,'not_checked')}</div><section class="card"><h2>Shared reconciliation</h2>${currentSession?`<p><strong>${esc(currentSession.name)}</strong></p><p class="muted">${assets.length} serialised stock records loaded.</p>`:`<label>Reconciliation name</label><input id="new-session-name" value="2026 Stock Reconciliation"><button id="create-session" class="full">Create shared reconciliation</button>`}</section>${currentSession?`<section class="card"><h2>Import latest SiSo stock list</h2><input id="csv-file" type="file" accept=".csv,text/csv"><button id="import-csv" class="full">Import serialised assets</button><div id="import-status" class="status hidden" aria-live="polite"></div></section>`:''}<section class="card"><div class="row"><div><strong>Technician</strong><div class="muted">${esc(technician)}</div></div><button id="change-tech" class="secondary">Change</button></div></section>`;}
const metric=(label:string,n:number,q:QueueStatus)=>`<button class="metric metric-button" data-queue="${q}"><span>${label}</span><strong>${n}</strong></button>`;
function reconcileHtml(){return `<section class="card"><h2>Photograph serial labels</h2><p class="muted">Choose one or several photos. OCR runs on this phone and images are not uploaded.</p><input id="ocr-files" type="file" accept="image/*" capture="environment" multiple><button id="run-ocr" class="full" ${!assets.length?'disabled':''}>Read photos</button><div id="ocr-status" class="status hidden" aria-live="polite"></div></section><section class="card"><h2>Manual serial fallback</h2><div class="row"><input id="manual-serial" autocomplete="off" autocapitalize="characters" placeholder="Enter serial"><button id="manual-search">Find</button></div></section>${candidateHtml()}`;}
function candidateHtml(){if(!candidates.length)return `<section class="card"><h2>Results</h2><p class="muted">OCR and manual matches appear here.</p></section>`;return `<section class="card"><h2>Batch results</h2>${candidates.map((c,i)=>candidateCard(c,i)).join('')}</section>`;}
function candidateCard(c:OcrCandidate,i:number){
  if(c.matches&&c.matches.length>1)return `<div class="asset"><span class="badge warn">${c.matches.length} SiSo matches</span><div class="asset-title">Serial ${esc(c.raw)}</div><p class="muted">The stock export contains this serial more than once. Select the item by its kit.</p>${c.matches.map((a,j)=>{const existing=resultFor(a.id);return `<div class="match-choice"><strong>${esc(a.asset_name)}</strong><div class="muted">${esc(a.make)} ${esc(a.model)}</div><div class="kit-label">Correct kit: ${esc(a.bag_label??a.barcode??'No SiSo barcode')}</div>${existing?`<div class="status">Already recorded by ${esc(existing.verified_by)}</div>`:`<div class="actions"><button data-match-outcome="already_correct" data-index="${i}" data-match="${j}">Already in correct kit</button><button data-match-outcome="returned" data-index="${i}" data-match="${j}">Returned to correct kit</button><button data-match-outcome="could_not_return" data-index="${i}" data-match="${j}" class="warn">Needs further action</button></div>`}</div>`}).join('')}</div>`;
  if(!c.asset)return `<div class="asset"><span class="badge bad">Not found</span><label>OCR text</label><div class="row"><input data-correct-index="${i}" value="${esc(c.raw)}"><button data-relookup="${i}" class="secondary">Try again</button></div><div class="actions"><button data-unknown="${i}" class="danger">Log for further action</button></div></div>`;
  const existing=resultFor(c.asset.id);return `<div class="asset"><span class="badge ${c.matchType==='exact'?'ok':'warn'}">${c.matchType==='exact'?'Matched':'Check OCR reading'}</span><div class="asset-title">${esc(c.asset.asset_name)}</div><div class="muted">${esc([c.asset.make,c.asset.model].filter(Boolean).join(' '))} · Serial ${esc(c.asset.serial)}</div><div class="kit-label">Correct kit: ${esc(c.asset.bag_label??c.asset.barcode??'No SiSo barcode')}</div>${c.matchType!=='exact'?`<label>Recognised text</label><div class="row"><input data-correct-index="${i}" value="${esc(c.raw)}"><button data-relookup="${i}" class="secondary">Correct</button></div>`:''}${existing?`<div class="status">Already recorded by ${esc(existing.verified_by)} · ${esc(existing.queue_status.replaceAll('_',' '))}</div>`:`<div class="actions"><button data-outcome="already_correct" data-index="${i}">Already in correct kit</button><button data-outcome="returned" data-index="${i}">Returned to correct kit</button><button data-outcome="could_not_return" data-index="${i}" class="warn">Needs further action</button></div>`}</div>`;
}
function bulkHtml(){const total=bulkCounts.reduce((s,c)=>s+(c.barcode_required?c.quantity:0),0);return `<section class="card"><h2>Bulk count</h2><label>Item type</label><input id="bulk-name" placeholder="Headphones"><label>Quantity found</label><input id="bulk-qty" type="number" min="1" inputmode="numeric"><label>Proposed QR prefix (optional)</label><input id="bulk-prefix" autocapitalize="characters" placeholder="HPS"><label>Label method</label><select id="bulk-method"><option value="small_adhesive">Small adhesive</option><option value="key_fob">Key fob</option><option value="standard_adhesive">Standard adhesive</option><option value="flag_label">Flag label</option><option value="pending">Decide later</option></select><label class="check"><input id="bulk-barcode" type="checkbox" checked> Needs an individual QR label per item</label><label>Notes</label><textarea id="bulk-notes" rows="2"></textarea><button id="save-bulk" class="full">Add to QR queue</button></section><section class="card"><h2>QR label queue</h2><p><strong>${total}</strong> labels required from bulk counts.</p>${bulkCounts.map(c=>`<div class="asset"><strong>${esc(c.item_name)}</strong> — ${c.quantity}<div class="muted">${esc(c.proposed_prefix??'No prefix yet')} · ${esc(c.label_method.replaceAll('_',' '))} · ${esc(c.counted_by)}</div></div>`).join('')||'<p class="muted">No bulk counts yet.</p>'}</section>`;}
function queueHtml(){const rows=queueFilter==='not_checked'?assets.filter(a=>!resultFor(a.id)).map(a=>({asset:a,result:null})):results.filter(r=>r.queue_status===queueFilter).map(r=>({asset:assets.find(a=>a.id===r.inventory_asset_id),result:r})).filter(x=>x.asset);return `<section class="card"><div class="row"><h2>${esc(queueFilter.replaceAll('_',' '))}</h2><button id="back-dashboard" class="secondary">Back</button></div>${rows.length?rows.map(({asset:a,result:r})=>`<div class="asset"><div class="asset-title">${esc(a!.asset_name)}</div><div class="muted">Serial ${esc(a!.serial)} · ${esc(a!.bag_label??a!.barcode??'No kit code')}</div>${r?`<div class="muted">${esc(r.exception_reason??r.outcome??'')} · ${esc(r.verified_by)}</div>${r.queue_status!=='reconciled'?`<button data-resolve="${r.id}" class="full">Mark resolved</button>`:''}`:''}</div>`).join(''):'<p class="muted">Nothing in this queue.</p>'}</section>`;}
function exportHtml(c:Record<QueueStatus,number>){const existing=assets.filter(a=>a.label_required).length,bulk=bulkCounts.reduce((s,x)=>s+(x.barcode_required?x.quantity:0),0);return `<section class="card"><h2>Export shared results</h2><div class="grid metrics">${metric('Existing QR labels',existing,'reconciled')}${metric('Bulk QR labels',bulk,'reconciled')}${metric('Second pass',c.second_pass,'second_pass')}${metric('Further action',c.further_action,'further_action')}</div><div class="actions"><button id="export-full">Full augmented CSV</button><button id="export-leftovers" class="secondary">Outstanding items</button><button id="export-bulk" class="secondary">Bulk QR queue</button></div></section>`;}
const navHtml=()=>`<nav><button data-view="dashboard" class="${activeView==='dashboard'?'active':''}">Dashboard</button><button data-view="reconcile" class="${activeView==='reconcile'?'active':''}">Reconcile</button><button data-view="bulk" class="${activeView==='bulk'?'active':''}">Bulk count</button><button data-view="export" class="${activeView==='export'?'active':''}">Export</button></nav>`;
function reasonModal(){return `<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><h2>Why can’t it be returned?</h2><div class="reason-grid"><button data-reason="Correct kit currently on loan" data-stage="second_pass">Correct kit currently on loan</button><button data-reason="Current kit currently on loan" data-stage="second_pass">Current kit currently on loan</button><button data-reason="Correct kit not found" data-stage="second_pass">Correct kit not found</button><button data-reason="Requires investigation" data-stage="further_action" class="warn">Requires investigation</button><button data-reason="Other" data-stage="further_action" class="secondary">Other</button><button id="cancel-reason" class="secondary">Cancel</button></div></section></div>`;}

function lookup(raw:string):OcrCandidate{const n=normalizeSerial(raw),by=new Map<string,InventoryAsset[]>();for(const a of assets)by.set(a.serial_normalized,[...(by.get(a.serial_normalized)??[]),a]);const exact=by.get(n),variant=exact?undefined:serialVariants(n).find(v=>by.has(v)),matches=exact??(variant?by.get(variant):undefined);return{raw,normalized:variant??n,confidence:100,asset:matches?.length===1?matches[0]:undefined,matches,matchType:exact?'exact':variant?'substitution':'none'};}
async function saveOutcome(c:OcrCandidate,outcome:ReconcileOutcome,reason:string|null=null,stage:'second_pass'|'further_action'='second_pass'){if(!c.asset||!currentSession)return;const queue:QueueStatus=outcome==='could_not_return'?stage:'reconciled';const record={inventory_asset_id:c.asset.id,audit_session_id:currentSession.id,queue_status:queue,audit_stage:queue==='reconciled'?'complete':stage,outcome,exception_reason:reason,next_action:queue==='second_pass'?'Recheck kit availability':queue==='further_action'?'Investigate or update SiSo':null,label_required:c.asset.label_required,label_method:c.asset.label_method,verified_by:technician,verified_at:new Date().toISOString()};const {error}=await supabase.from('audit_results').upsert(record,{onConflict:'inventory_asset_id'});if(error)alert(error.message);pendingCandidate=null;await loadSessionData();render();}

function bindEvents(){
 document.querySelector('#save-tech')?.addEventListener('click',()=>{const v=(document.querySelector<HTMLInputElement>('#tech')?.value??'').trim();if(v){technician=v;localStorage.setItem('siso-technician',v);render();}});
 document.querySelector('#change-tech')?.addEventListener('click',()=>{technician='';localStorage.removeItem('siso-technician');render();});
 document.querySelector('#change-session')?.addEventListener('click',()=>{localStorage.removeItem('siso-session');currentSession=null;render();});
 document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.addEventListener('click',()=>{activeView=b.dataset.view as typeof activeView;render();}));
 document.querySelectorAll<HTMLButtonElement>('[data-queue]').forEach(b=>b.addEventListener('click',()=>{queueFilter=b.dataset.queue as QueueStatus;activeView='queue';render();}));
 document.querySelector('#back-dashboard')?.addEventListener('click',()=>{activeView='dashboard';render();});
 document.querySelector('#create-session')?.addEventListener('click',async()=>{const name=(document.querySelector<HTMLInputElement>('#new-session-name')?.value??'').trim();if(!name)return;const {data,error}=await supabase.from('audit_sessions').insert({name,created_by:technician}).select().single();if(error)alert(error.message);else{localStorage.setItem('siso-session',data.id);await refresh();}});
 document.querySelector('#import-csv')?.addEventListener('click',async()=>{const file=document.querySelector<HTMLInputElement>('#csv-file')?.files?.[0],status=document.querySelector<HTMLDivElement>('#import-status');if(!file||!currentSession||!status)return;status.classList.remove('hidden');status.textContent='Importing…';try{const r=await importInventoryCsv(file,currentSession.id);status.textContent=`Imported ${r.imported}; skipped ${r.skippedNoSerial} without serials; ${r.duplicateSerials} duplicate serial rows.`;await loadSessionData();render();}catch(e){status.textContent=e instanceof Error?e.message:String(e);}});
 document.querySelector('#run-ocr')?.addEventListener('click',async()=>{const files=[...(document.querySelector<HTMLInputElement>('#ocr-files')?.files??[])],status=document.querySelector<HTMLDivElement>('#ocr-status');if(!files.length||!status)return;status.classList.remove('hidden');try{candidates=await recogniseFiles(files,assets,m=>status.textContent=m);status.textContent=`Found ${candidates.length} candidate serials.`;render();}catch(e){status.textContent=e instanceof Error?e.message:String(e);}});
 document.querySelector('#manual-search')?.addEventListener('click',()=>{const raw=(document.querySelector<HTMLInputElement>('#manual-serial')?.value??'').trim();if(raw){candidates=[lookup(raw),...candidates];render();}});
 document.querySelectorAll<HTMLButtonElement>('[data-relookup]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.relookup),raw=document.querySelector<HTMLInputElement>(`[data-correct-index="${i}"]`)?.value??'';candidates[i]=lookup(raw);render();}));
 document.querySelectorAll<HTMLButtonElement>('[data-match-outcome]').forEach(b=>b.addEventListener('click',()=>{const base=candidates[Number(b.dataset.index)],asset=base?.matches?.[Number(b.dataset.match)];if(!base||!asset)return;const c={...base,asset,matches:[asset]};const o=b.dataset.matchOutcome as ReconcileOutcome;if(o==='could_not_return'){pendingCandidate=c;render();}else saveOutcome(c,o);}));
 document.querySelectorAll<HTMLButtonElement>('[data-outcome]').forEach(b=>b.addEventListener('click',()=>{const c=candidates[Number(b.dataset.index)];if(!c)return;const o=b.dataset.outcome as ReconcileOutcome;if(o==='could_not_return'){pendingCandidate=c;render();}else saveOutcome(c,o);}));
 document.querySelectorAll<HTMLButtonElement>('[data-reason]').forEach(b=>b.addEventListener('click',()=>{if(pendingCandidate)saveOutcome(pendingCandidate,'could_not_return',b.dataset.reason??'Other',b.dataset.stage as 'second_pass'|'further_action');}));
 document.querySelector('#cancel-reason')?.addEventListener('click',()=>{pendingCandidate=null;render();});
 document.querySelectorAll<HTMLButtonElement>('[data-unknown]').forEach(b=>b.addEventListener('click',async()=>{if(!currentSession)return;const c=candidates[Number(b.dataset.unknown)];if(!c)return;const {error}=await supabase.from('unknown_serials').insert({audit_session_id:currentSession.id,raw_serial:c.raw,normalized_serial:c.normalized,source:'ocr',queue_status:'further_action',reported_by:technician});if(error)alert(error.message);else alert('Logged for further action.');}));
 document.querySelectorAll<HTMLButtonElement>('[data-resolve]').forEach(b=>b.addEventListener('click',async()=>{const {error}=await supabase.from('audit_results').update({queue_status:'reconciled',audit_stage:'complete',next_action:null,updated_at:new Date().toISOString()}).eq('id',b.dataset.resolve);if(error)alert(error.message);await loadSessionData();render();}));
 document.querySelector('#save-bulk')?.addEventListener('click',async()=>{if(!currentSession)return;const name=(document.querySelector<HTMLInputElement>('#bulk-name')?.value??'').trim(),quantity=Number(document.querySelector<HTMLInputElement>('#bulk-qty')?.value??0);if(!name||quantity<1)return;const record={audit_session_id:currentSession.id,item_name:name,asset_type:name,quantity,barcode_required:document.querySelector<HTMLInputElement>('#bulk-barcode')?.checked??true,proposed_prefix:(document.querySelector<HTMLInputElement>('#bulk-prefix')?.value??'').trim().toUpperCase()||null,label_method:document.querySelector<HTMLSelectElement>('#bulk-method')?.value??'pending',queue_status:'barcode_queue',notes:(document.querySelector<HTMLTextAreaElement>('#bulk-notes')?.value??'').trim()||null,counted_by:technician};const {error}=await supabase.from('bulk_counts').insert(record);if(error)alert(error.message);await loadSessionData();render();});
 document.querySelector('#export-full')?.addEventListener('click',()=>downloadCsv('siso-companion-full-audit.csv',augmentedRows(assets,results)));
 document.querySelector('#export-leftovers')?.addEventListener('click',()=>downloadCsv('siso-companion-outstanding.csv',augmentedRows(assets,results).filter((_,i)=>{const r=resultFor(assets[i]!.id);return !r||r.queue_status==='second_pass'||r.queue_status==='further_action';})));
 document.querySelector('#export-bulk')?.addEventListener('click',()=>downloadCsv('siso-companion-bulk-qr-queue.csv',bulkBarcodeRows(bulkCounts)));
}
async function subscribe(){if(realtimeChannel)await supabase.removeChannel(realtimeChannel);if(!currentSession)return;realtimeChannel=supabase.channel(`audit:${currentSession.id}`).on('postgres_changes',{event:'*',schema:'public',table:'audit_results',filter:`audit_session_id=eq.${currentSession.id}`},async()=>{await loadSessionData();render();}).on('postgres_changes',{event:'*',schema:'public',table:'bulk_counts',filter:`audit_session_id=eq.${currentSession.id}`},async()=>{await loadSessionData();render();}).on('postgres_changes',{event:'*',schema:'public',table:'unknown_serials',filter:`audit_session_id=eq.${currentSession.id}`},async()=>render()).subscribe();}
async function refresh(){await loadSessions();await loadSessionData();render();await subscribe();}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(console.error));
(async()=>{try{await ensureAnonymousSession();await refresh();}catch(e){app.innerHTML=`<div class="shell"><main><section class="card"><h2>Setup error</h2><p>${esc(e instanceof Error?e.message:String(e))}</p></section></main></div>`;}})();
