-- SiSo Companion v0.2 schema. This matches the pilot schema installed in Supabase.
create extension if not exists pgcrypto;
create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;
create table if not exists public.audit_sessions(id uuid primary key default gen_random_uuid(),name text not null,status text not null default 'open' check(status in('open','archived')),created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.label_profiles(id uuid primary key default gen_random_uuid(),asset_type text not null,prefix text not null unique,description text,label_method text not null default 'pending' check(label_method in('key_fob','small_adhesive','standard_adhesive','wrap_around','flag_label','pending')),number_padding integer not null default 3 check(number_padding between 2 and 8),next_number integer not null default 1 check(next_number>0),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inventory_assets(id uuid primary key default gen_random_uuid(),audit_session_id uuid not null references public.audit_sessions(id) on delete cascade,source_row integer,siso_asset_id text,asset_name text not null,description text,category text,asset_type text,make text,model text,serial text not null,serial_normalized text not null,barcode text,bag_label text,label_required boolean not null default true,label_status text not null default 'required' check(label_status in('not_required','required','planned','generated','printed','applied','verified')),label_method text not null default 'pending' check(label_method in('key_fob','small_adhesive','standard_adhesive','wrap_around','flag_label','pending')),label_profile_id uuid references public.label_profiles(id) on delete set null,original_row jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(audit_session_id,source_row));
create table if not exists public.audit_results(id uuid primary key default gen_random_uuid(),inventory_asset_id uuid not null unique references public.inventory_assets(id) on delete cascade,audit_session_id uuid not null references public.audit_sessions(id) on delete cascade,queue_status text not null check(queue_status in('not_checked','reconciled','second_pass','further_action')),audit_stage text not null default 'first_pass' check(audit_stage in('first_pass','second_pass','further_action','complete')),outcome text check(outcome in('already_correct','returned','could_not_return')),exception_reason text,next_action text,label_required boolean not null default false,label_method text,last_seen_zone text,verified_by text not null,verified_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.bulk_counts(id uuid primary key default gen_random_uuid(),audit_session_id uuid not null references public.audit_sessions(id) on delete cascade,item_name text not null,asset_type text,quantity integer not null check(quantity>0),barcode_required boolean not null default true,label_profile_id uuid references public.label_profiles(id) on delete set null,proposed_prefix text,proposed_start_number integer,proposed_end_number integer,label_method text not null default 'pending',queue_status text not null default 'barcode_queue',notes text,counted_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.unknown_serials(id uuid primary key default gen_random_uuid(),audit_session_id uuid not null references public.audit_sessions(id) on delete cascade,raw_serial text not null,normalized_serial text not null,source text not null default 'ocr',queue_status text not null default 'second_pass',notes text,reported_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists inventory_assets_session_idx on public.inventory_assets(audit_session_id); create index if not exists inventory_assets_serial_idx on public.inventory_assets(audit_session_id,serial_normalized); create index if not exists audit_results_session_idx on public.audit_results(audit_session_id); create index if not exists bulk_counts_session_idx on public.bulk_counts(audit_session_id);
alter table public.audit_sessions enable row level security; alter table public.label_profiles enable row level security; alter table public.inventory_assets enable row level security; alter table public.audit_results enable row level security; alter table public.bulk_counts enable row level security; alter table public.unknown_serials enable row level security;
do $$ declare t text; begin foreach t in array array['audit_sessions','label_profiles','inventory_assets','audit_results','bulk_counts','unknown_serials'] loop execute format('drop policy if exists "pilot read" on public.%I',t); execute format('drop policy if exists "pilot insert" on public.%I',t); execute format('drop policy if exists "pilot update" on public.%I',t); execute format('create policy "pilot read" on public.%I for select to authenticated using (true)',t); execute format('create policy "pilot insert" on public.%I for insert to authenticated with check (true)',t); execute format('create policy "pilot update" on public.%I for update to authenticated using (true) with check (true)',t); end loop; end $$;
do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='audit_results') then alter publication supabase_realtime add table public.audit_results; end if; if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='bulk_counts') then alter publication supabase_realtime add table public.bulk_counts; end if; if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='unknown_serials') then alter publication supabase_realtime add table public.unknown_serials; end if; end $$;
insert into public.label_profiles(asset_type,prefix,description,label_method) values('Headphones','HPS','Individually labelled headphones','small_adhesive'),('SD Card Reader','SDR','Individually labelled SD card readers','small_adhesive'),('XLR Cable','XLR','Individually labelled XLR cables','flag_label') on conflict(prefix) do nothing;
